doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: false
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

            Core:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Services/Core/Domain'
                prefix: 'App\Services\Core\Domain'
                alias: Core

            User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Services/User/Domain'
                prefix: 'App\Services\User\Domain'
                alias: User

            Puzzle:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Services/Puzzle/Domain'
                prefix: 'App\Services\Puzzle\Domain'
                alias: Puzzle

            Quotation:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Services/Quotation/Domain'
                prefix: 'App\Services\Quotation\Domain'
                alias: Quotation

            Abuse:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Services/Abuse/Domain'
                prefix: 'App\Services\Abuse\Domain'
                alias: Abuse

            BlockedEmailAddress:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Services/BlockedEmailAddress/Domain'
                prefix: 'App\Services\BlockedEmailAddress\Domain'
                alias: BlockedEmailAddress

            BugReport:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Services/BugReport/Domain'
                prefix: 'App\Services\BugReport\Domain'
                alias: BugReport

            Game:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Services/Game/Domain'
                prefix: 'App\Services\Game\Domain'
                alias: BugReport
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
